title: New Network Routes Detected
id: c803b2ce-c4a2-4836-beae-b112010390b1
status: test
author: jamesc-grafana
description: |
  Detects when new network routes are added to a route table in AWS
references:
  - https://www.gorillastack.com/blog/real-time-events/important-aws-cloudtrail-security-events-tracking/
date: 2024/04/02
tags:
  - attack.initial_access
  - attack.t1190
logsource:
  product: aws
  service: ec2
detection:
  selection:
    eventSource: ec2.amazonaws.com
    eventName: CreateRoute
  condition: selection
falsepositives:
  - New VPC Creation requiring setup of a new route table
  - New subnets added requiring routing setup
level: medium
