title: Detection of Potential Malicious Guest Accounts and RMM Tool Deployment via Teams
id: aed9c24f-097a-4505-af85-74b4b83982b0
status: experimental
description: Detects potential malicious guest accounts using onmicrosoft.com and deployment of RMM tools via Teams messages.
references:
    - https://securityaffairs.com/170311/cyber-crime/black-basta-ransomware-microsoft-teams.html
    - https://www.bleepingcomputer.com/news/security/black-basta-ransomware-poses-as-it-support-on-microsoft-teams-to-breach-networks/
author: Enter the author name
date: 2024-11-01
tags:
    - attack.initial-access
    - attack.t1078
    - attack.execution
    - attack.persistence
    - attack.t1133
    - attack.defense-evasion
    - attack.t1070
    - attack.collection
    - attack.t1114
logsource:
    product: m365
    service: audit
detection:
    selection_domain:
        user.email: '*@*.onmicrosoft.com'
    selection_extensions:
        o365.audit.MessageURLs|endswith:
            - .exe
            - .msi
            - .js
    selection_rmm:
        o365.audit.MessageURLs:
            - ninjaone.com
            - atera.com
            - syncroweb.com
            - superops.com
            - n-able.com
            - gotoremember.com
            - barracudamsp.com
            - manageengine.com
            - site24x7.com
            - paessler.com
            - compuware.com
            - teamviewer.com
            - rippling.com
            - msp360.com
            - pulseway.com
            - optimtune.com
            - connectwise.com
            - domotz.com
            - anydesk.com
    condition: selection_domain and (selection_extensions or selection_rmm)
falsepositives:
    - Legitimate guest users
    - Valid RMM tool deployments
level: high
